### ISSUE TITLE
NoMethodError (undefined method `value' for #<SimpleFeed::Response:...>) when trying to delete_if

### ISSUE THREAD

**Issue by llukyanov** [kigster/simple-feed#22]
Hello, I've created a feed and am trying to delete activity from it via the "delete_if" block, however am getting an undefined method 'value' error.

**Comment by kigster** [comment]
Could you please paste the block where you are deleting it, and the top five stack strace?

**Comment by llukyanov** [comment]
Below is the block. The SimpleFeed is named "Newsfeed" and contains data of the format {:activity_type => (ex. 'posting;), :activity_id=> (ex. 1),  :user_id=> (ex. 1)}
		

		follower = follow_activity.user
		following = follow_activity.following

		follower_feed = SimpleFeed.newsfeed.activity(follower.id)
		follower_feed.delete_if do |event, user_id|
			event.value =~ /\"user_id\"=>#{following.id}/
		end

And here is the strace:

> Traceback (most recent call last):
>         3: from (irb):5
>         2: from app/lib/newsfeed.rb:94:in `update_after_unfollow'
>         1: from app/lib/newsfeed.rb:95:in `block in update_after_unfollow'
> NoMethodError (undefined method `value' for #<SimpleFeed::Response:0x00007f7f76572680>)
> Did you mean?  values
>                value?

Thank you!

**Comment by kigster** [comment]
Thanks!
